apiVersion: v1
kind: Service
metadata:
  name: changedetection
  namespace: changedetection
spec:
  type: LoadBalancer
  selector:
    app: changedetection
  ports:
    - name: "port-5005"
      port: 5005
      targetPort: 5000
