apiVersion: v1
kind: Service
metadata:
  name: planka
  namespace: planka
spec:
  type: LoadBalancer
  selector:
    app: planka
  ports:
    - name: port-1337
      port: 1337 #custom port
      targetPort: 1337