apiVersion: v1
kind: Service
metadata:
  name: wallos
  namespace: wallos
spec:
  type: NodePort
  externalIPs:
  - 192.168.0.100
  - 192.168.0.101
  selector:
    app: wallos
  ports:
    - name: "80"
      port: 8282
      targetPort: 80
