apiVersion: v1
kind: Service
metadata:
  name: wallos
  namespace: wallos
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: wallos
  ports:
    - name: "80"
      port: 8282
      targetPort: 80
