apiVersion: v1
kind: Namespace
metadata:
  name: pihole

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-generic-configmap
  namespace: pihole
data:
  TZ: Europe/Amsterdam
  DNS1: 127.0.0.1#5335
  VIRTUAL_HOST: #The virtual host for Pi-hole (e.g., pi-hole.example.com).
  QUERY_LOGGING: "false"
  FTLCONF_PRIVACYLEVEL: "3"
  FTLCONF_DBIMPORT: "no"
  FTLCONF_MAXDBDAYS: "7"
  FTLCONF_DBINTERVAL: "60"

---

apiVersion: v1
kind: Secret
metadata:
  name: pihole-generic-secrets
  namespace: pihole
type: Opaque
data:
  WEBPASSWORD: #The base64-encoded password for the Pi-hole web interface.
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostname: pihole
      volumes:
      - name: config
        hostPath:
          path: /mnt/data/pihole/settings
          type: DirectoryOrCreate
      - name: dnsmasq
        hostPath:
          path: /mnt/data/pihole/dnsmasq
          type: DirectoryOrCreate
      - name: conf-unbound
        hostPath:
          path: /mnt/data/pihole/unbound/unbound.conf
          type: FileOrCreate
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: pihole-generic-configmap
        - secretRef:
            name: pihole-generic-secrets
        ports:
        - containerPort: 53
        - containerPort: 67
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/pihole
        - name: dnsmasq  
          mountPath: /etc/dnsmasq.d
        livenessProbe:
          httpGet:
            path: /admin
            port: 80
        readinessProbe:
          httpGet:
            path: /admin
            port: 80
        resources: {}
      - name: unbound
        image: klutchell/unbound:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 5335
        volumeMounts:
        - name: conf-unbound
          mountPath: /etc/unbound/unbound.conf
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  type: NodePort
  externalIPs:
  - #The cluster IP addres: (e.g., 192.168.0.1).
  selector:
    app: pihole
  ports:
    - name: port-53-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: port-53-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: port-67-udp
      protocol: UDP
      port: 67
      targetPort: 67
    - name: port-80-tcp
      protocol: TCP
      port: 8080
      targetPort: 80
