apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: immich
spec:
  type: LoadBalancer
  selector:
    app: immich
  ports:
    - name: "port-2283"
      port: 2283
      targetPort: 3001
