apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: immich
spec:
  type: NodePort
  externalIPs:
  - 192.168.0.100
  - 192.168.0.101
  selector:
    app: immich
  ports:
    - name: "port-2283"
      port: 2283
      targetPort: 3001
