apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: open-webui
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: open-webui
  ports:
    - name: "port-8080"
      port: 5626
      targetPort: 8080
