apiVersion: v1
kind: Service
metadata:
  name: swag
  namespace: swag
spec:
  type: NodePort
  externalIPs:
  - 192.168.0.100
  - 192.168.0.101
  selector:
    app: swag
  ports:
    - name: "port-443-internal"
      port: 443
      targetPort: 443
    - name: "port-8443-external"
      port: 8443
      targetPort: 8443