apiVersion: v1
kind: Service
metadata:
  name: p1monitor
  namespace: p1monitor
spec:
  type: NodePort
  externalIPs:
  - 192.168.0.100
  - 192.168.0.101
  selector:
    app: p1monitor
  ports:
    - name: "80"
      port: 8989
      targetPort: 80
