apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: p1monitor
  name: p1monitor
  namespace: p1monitor
spec:
  serviceName: "p1monitor"
  replicas: 1
  selector:
    matchLabels:
      app: p1monitor
  template:
    metadata:
      labels:
        app: p1monitor
    spec:
      hostname: p1monitor
      volumes:
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0
        # - name: gpiomem
        #   hostPath:
        #     path: /dev/gpiomem
        - name: p1monitor-data
          hostPath:
            path: /mnt/data/p1monitor/data
        - name: p1monitor-run
          emptyDir:
            medium: Memory
        - name: p1monitor-tmp
          emptyDir:
            medium: Memory
        - name: p1monitor-ramdisk
          emptyDir:
            medium: Memory
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      containers:
        - image: mclaassen/p1mon:latest
          name: p1monitor
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - name: ttyusb
              mountPath: /dev/ttyUSB0
            # - name: gpiomem
            #   mountPath: /dev/gpiomem
            - name: p1monitor-data
              mountPath: /p1mon/data
            - name: p1monitor-run
              mountPath: /run
            - name: p1monitor-tmp
              mountPath: /tmp
            - name: p1monitor-ramdisk
              mountPath: /p1mon/mnt/ramdisk
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources: {}
