apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress: []

