apiVersion: v1
kind: Service
metadata:
  name: obsidian
  namespace: obsidian
spec:
  type: NodePort
  externalIPs:
  - 192.168.0.100
  - 192.168.0.101
  selector:
    app: obsidian
  ports:
    - name: "port-5984"
      port: 59840
      targetPort: 5984
