apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: homebridge
  ports:
    - name: "port-8581"
      port: 8580
      targetPort: 8581
