apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  type: NodePort
  externalIPs:
  - 192.168.0.100
  - 192.168.0.101
  selector:
    app: homebridge
  ports:
    - name: "port-8581"
      port: 8580
      targetPort: 8581
