apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: syncthing
  ports:
    - name: "port-8384-tcp"
      port: 8384
      targetPort: 8384
    - name: "port-22000"
      port: 22000
      targetPort: 22000
    - name: "port-21027"
      port: 21027
      targetPort: 21027
