apiVersion: v1
kind: Service
metadata:
  name: karakeep
  namespace: karakeep
spec:
  type: LoadBalancer
  selector:
    app: karakeep
  ports:
    - name: port-3000
      port: 3000
      targetPort: 3000